# AllGenerics.R
# Setting all Generic Functions
# Author: Ben Neely <nigelneely@gmail.com>
#############################################
setGeneric(name=".setConfig",
           def=function(Object)
           {
             standardGeneric(".setConfig")
           }
)
setGeneric(name=".saveConfig",
           def=function(Object)
           {
             standardGeneric(".saveConfig")
           }
)
setGeneric(name=".readConfig",
           def=function(Object)
           {
             standardGeneric(".readConfig")
           }
)

setGeneric(name=".deleteConfig",
           def=function(Object)
           {
             standardGeneric(".deleteConfig")
           }
)
setGeneric(name=".get",
           def=function(Object)
           {
             standardGeneric(".get")
           }
)
setGeneric(name=".post",
           def=function(Object)
           {
             standardGeneric(".post")
           }
)
setGeneric(name=".put",
           def=function(Object)
           {
             standardGeneric(".put")
           }
)
setGeneric(name=".delete",
           def=function(Object)
           {
             standardGeneric(".delete")
           }
)
setGeneric(name="ddsprint",
           def=function(Object)
           {
             standardGeneric("ddsprint")
           }
)
setGeneric(name=".createINIText",
           def=function(Object)
           {
             standardGeneric(".createINIText")
           }
)
setGeneric(name=".loadConfigFromCache",
           def=function(Object)
           {
             standardGeneric(".loadConfigFromCache")
           }
)
setGeneric(name=".getFileNamesIntoList",
           def=function(Object)
           {
             standardGeneric(".getFileNamesIntoList")
           }
)
setGeneric(name=".getDDSProjectId",
           def=function(Object)
           {
             standardGeneric(".getDDSProjectId")
           }
)
setGeneric(name=".getLocalHash",
           def=function(Object)
           {
             standardGeneric(".getLocalHash")
           }
)
setGeneric(name=".createDDSFolders",
           def=function(Object,...)
           {
             standardGeneric(".createDDSFolders")
           }
)
setGeneric(name=".createLocalFolders",
           def=function(Object,...)
           {
             standardGeneric(".createLocalFolders")
           }
)
